sudo: required
addons:
  hosts:
    - boundless-test
services:
    - docker
env:
    - PLUGIN_NAME=milstd2525
before_install:
    - docker pull elpaso/qgis-testing-environment:latest
    - docker tag elpaso/qgis-testing-environment:latest qgis-testing-environment
install:
    - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 qgis-testing-environment
    - sleep 10

    # Setup QGIS to avoid modals and install test auth db
    - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"

    # Build the plugin
    - docker exec -it qgis-testing-environment sh -c "pip install paver"
    - docker exec -it qgis-testing-environment sh -c "cd /tests_directory && paver setup"
    - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory/${PLUGIN_NAME} /root/.qgis2/python/plugins/${PLUGIN_NAME}"

script:
    # Run the unit tests
    # This plugin has not yet any unit tests
    - docker exec -it qgis-testing-environment sh -c "echo '${PLUGIN_NAME} has no unit tests yet, please create them and add here'"

